// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Platform Default FirebaseOptions are auto-generated for iOS and Android
/// by running `flutterfire configure` on your Flutter project.
/// For other platforms, default [FirebaseOptions] need to be manually created.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjiJDuTUEKCkFdH00bXewESmBK4FUQam8',
    appId: '1:33620163082:web:7f24881bd10468baa03df3',
    messagingSenderId: '33620163082',
    projectId: 'adstab-e418e',
    authDomain: 'adstab-e418e.firebaseapp.com',
    storageBucket: 'adstab-e418e.firebasestorage.app',
    measurementId: 'G-XM5462670R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvrPWIO8DmHa6bEhiaiBYlnCzeb0sx2o',
    appId: '1:33620163082:android:3e1ec299c8718ff2a03df3',
    messagingSenderId: '33620163082',
    projectId: 'adstab-e418e',
    storageBucket: 'adstab-e418e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe39IVjjMcmNF4WtQoHUQZjoWRehR2FcQ',
    appId: '1:33620163082:ios:8d6f7f7507d09201a03df3',
    messagingSenderId: '33620163082',
    projectId: 'adstab-e418e',
    storageBucket: 'adstab-e418e.firebasestorage.app',
    iosBundleId: 'com.adstap',
  );

}